### ISSUE TITLE
Error in test:html, test:images

### ISSUE THREAD

**Issue by micwoj92** [ttscoff/curlyq#1]
I suspect this is due to site redesign? I succesfully did these checks last time around 1 month ago, below log of test:html:
```
** Invoke test:html (first_time)
** Execute test:html
Loaded suite /usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader
Started
E
===============================================================================
Error: test_html_search_query(CurlyQHtmlTest):
  RuntimeError: Error (pid 1081 exit 1): ["bin/curlyq", "html", "-s", "#main article .aligncenter", "-q", "images[1]", "https://brettterpstra.com"] failed
  STDOUT:
  ""
  STDERR:
  "error: undefined method `ensure_array' for nil:NilClass\n/build/curlyq/src/curlyq-0.0.12/tmp_install/usr/lib/ruby/gems/3.2.0/gems/curlyq-0.0.12/lib/curly/array.rb:183:in `clean_output': undefined method `ensure_array' for nil:NilClass (NoMethodError)\n\n    output.ensure_array\n          ^^^^^^^^^^^^^\n\tfrom bin/curlyq:153:in `block (2 levels) in <main>'\n\tfrom /usr/lib/ruby/gems/3.2.0/gems/gli-2.21.5/lib/gli/command_support.rb:131:in `execute'\n\tfrom /usr/lib/ruby/gems/3.2.0/gems/gli-2.21.5/lib/gli/app_support.rb:298:in `block in call_command'\n\tfrom /usr/lib/ruby/gems/3.2.0/gems/gli-2.21.5/lib/gli/app_support.rb:311:in `call_command'\n\tfrom /usr/lib/ruby/gems/3.2.0/gems/gli-2.21.5/lib/gli/app_support.rb:85:in `run'\n\tfrom bin/curlyq:649:in `<main>'\n"
/build/curlyq/src/curlyq-0.0.12/test/helpers/curlyq-helpers.rb:22:in `pread'
/build/curlyq/src/curlyq-0.0.12/test/helpers/curlyq-helpers.rb:12:in `curlyq_with_env'
/build/curlyq/src/curlyq-0.0.12/test/helpers/curlyq-helpers.rb:16:in `curlyq'
/build/curlyq/src/curlyq-0.0.12/test/curlyq_html_test.rb:14:in `test_html_search_query'
     11:   include CurlyQHelpers
     12: 
     13:   def test_html_search_query
  => 14:     result = curlyq('html', '-s', '#main article .aligncenter', '-q', 'images[1]', 'https://brettterpstra.com')
     15:     json = JSON.parse(result)
     16: 
     17:     assert_match(/aligncenter/, json[0]['class'], 'Should have found an image with class "aligncenter"')
===============================================================================
Finished in 1.984630978 seconds.
-------------------------------------------------------------------------------
2 tests, 1 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
50% passed
-------------------------------------------------------------------------------
1.01 tests/s, 0.50 assertions/s
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test:test/helpers" /usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/rake_test_loader.rb "test/curlyq_html_test.rb" ]
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/testtask.rb:130:in `block (3 levels) in define'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/file_utils.rb:57:in `sh'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/file_utils.rb:104:in `ruby'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/testtask.rb:117:in `block (2 levels) in define'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/file_utils_ext.rb:58:in `verbose'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/testtask.rb:111:in `block in define'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/lib/ruby/gems/3.2.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/bin/rake:25:in `load'
/usr/bin/rake:25:in `<main>'
Tasks: TOP => test:html
```

**Comment by micwoj92** [comment]
Ping @ttscoff

**Comment by ttscoff** [comment]
Thanks for the report, will look into it when I get a chance.

**Comment by ttscoff** [comment]
Oh, yeah, this is totally because of site redesign. Will update tests soon.

**Comment by ttscoff** [comment]
Fixed both html and images tests, handles empty results better and deals with site redesign.

**Comment by micwoj92** [comment]
Thanks, I ran into different issue, opened #2.
