### ISSUE TITLE
Error running rake

### ISSUE THREAD

**Issue by micwoj92** [ttscoff/curlyq#2]
I tried to run tests again after #1 was fixed. However now I am unable to run them at all.
The difference is that now I am running 3.3.5 ruby and rake 13.1.0, it worked well with 3.2.5 and rake 13.0.6.
```
rake aborted!
LoadError: cannot load such file -- (eval at /build/curlyq/src/curlyq-0.0.15/lib/curly/version.rb (LoadError)
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
<internal:/usr/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:136:in `require'
(eval at /build/curlyq/src/curlyq-0.0.15/Rakefile:25):2:in `<top (required)>'
/build/curlyq/src/curlyq-0.0.15/Rakefile:25:in `eval'
/build/curlyq/src/curlyq-0.0.15/Rakefile:25:in `<top (required)>'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:734:in `raw_load_rakefile'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:126:in `block in load_rakefile'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:125:in `load_rakefile'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:82:in `block in run'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:208:in `standard_exception_handling'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/lib/rake/application.rb:80:in `run'
/usr/lib/ruby/gems/3.3.0/gems/rake-13.1.0/exe/rake:27:in `<top (required)>'
/usr/bin/rake:25:in `load'
/usr/bin/rake:25:in `<main>'
```

**Comment by ttscoff** [comment]
Are you using the latest version? There were permissions issues in the first push after I fixed the tests that may be causing the inability to load files. Tag 0.0.15 was the version with the fix for that.

**Comment by micwoj92** [comment]
I tried with 0.0.12 and 0.0.15, same result.

**Comment by ttscoff** [comment]
Is this with running `rake test` or running `curlyq` itself?

**Comment by micwoj92** [comment]
`rake test`

**Comment by ttscoff** [comment]
I'll have to install 3.3.5 and see if there's something up there. It doesn't make much sense that 3.1 vs 3.5 would cause a `LoadError`, but I'll test.

**Comment by ttscoff** [comment]
If you're able to switch ruby versions easily, does `rake test` still work with 3.2.5?

**Comment by ttscoff** [comment]
Huh, I _am_ able to replicate the issue in 3.3.5. I have no idea why that would be…

**Comment by ttscoff** [comment]
And if I remove offending lines and finally get tests to run…

![](https://share.cleanshot.com/MldPgS5N+)

I'm just going to say that for the time being curlyq is incompatible with 3.3.5 until I can figure out what changed.

**Comment by ttscoff** [comment]
But curlyq still seems to work, even if the Rakefile throws errors. This one is a bit baffling, I can't find any changes in 3.3 that would cause version.rb to error, given it's 3 lines of code that are syntactically correct (AFAICT). If you have any thoughts, I'd love to hear them.

**Comment by micwoj92** [comment]
I will try building 3.4.0 preview and using that

**Comment by micwoj92** [comment]
Same issue with ruby-3.4.0-preview2

So for me latest version it works is 3.2.5. I will try to narrow it down what exactly caused this issue this weekend.

**Comment by micwoj92** [comment]
It's because of this change:
https://github.com/ruby/ruby/commit/43a5c191358699fe8b19314763998cb8ca77ed90

**Comment by ttscoff** [comment]
> It's because of this change: [ruby/ruby@43a5c19](https://github.com/ruby/ruby/commit/43a5c191358699fe8b19314763998cb8ca77ed90)

Help me understand how this affects the Rakefile. What do I need to change?

**Comment by micwoj92** [comment]
I wish I knew that. I only did get to this change with git bisect. I also checked linked pr and issues but can't make sense of it.

**Comment by micwoj92** [comment]
I've just retested with:
```
ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]
ruby 4.0.0preview2 (2025-11-17 master 4fa6e9938c) +PRISM [x86_64-linux]
```
Rake still fails, although curlyq itself seems to work fine on ruby 4 preview

**Comment by ttscoff** [comment]
Yeah, I honestly haven't had a chance to touch it for a while. Rake is failing all tasks for me right now. I'll try to dig back into it after I get my current apps released.
